# Generated by Django 3.2.7 on 2021-09-16 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_1', models.CharField(max_length=100)),
                ('last_name_2', models.CharField(max_length=100)),
                ('cedula', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('genero', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('employee_number', models.IntegerField()),
                ('employee_title', models.CharField(max_length=50)),
                ('number_jefe', models.IntegerField()),
                ('zona', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
                ('ventas_2019', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('picture', models.ImageField(blank=True, max_length=200, null=True, upload_to='pictures/', verbose_name='Imagen de Perfil')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
